name = "images"
type = "javascript"
route = 'images.tuxsnct.com/*'
zone_id = 'b8be62d2bdbf2710249429aea588a14e'
usage_model = ''
compatibility_flags = []
workers_dev = false
compatibility_date = "2022-02-17"

[build]
# eslint-disable-next-line max-len
command = "mkdirp ./dist && esbuild ./src/main.ts --outfile=./dist/worker.js --bundle --minify --legal-comments=external --metafile=./dist/meta.json"

[build.upload]
format = "service-worker"
